"""Tree decomposition of a philosophical text.

The LLM decides whether to analyze a chunk directly or split it
into sub-sections by paragraph range. The framework slices the
text — no JSON reproduction of the document.

    uv run python examples/tree_decomposition.py

Uses Nietzsche's first essay from On the Genealogy of Morals
("Good and Evil," "Good and Bad") — bundled in examples/data/.
"""

import asyncio
import sys
import os
from pathlib import Path

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))

from motif import system, user, Block
from motif import flow
from motif.display import Trace, LiveFlowDisplay

# --- Prompts ---

SPLITTER = system("""You are analyzing a text that has been split into paragraphs
(numbered from 0). Decide whether to analyze the passage as one unit or
split it into 2-4 thematic sections.

If splitting, specify each section by its start and end paragraph numbers.
Prefer fewer, larger chunks. Only split where the argument genuinely shifts.

The text will tell you how many paragraphs it has.""", cache=True)

ANALYZER = system("""You are a philosophical reader performing close analysis.
Identify: (1) the core claim, (2) the argumentative strategy,
(3) what the passage assumes without stating, (4) one thing a
surface reading would miss. 200-300 words.""", cache=True)

MERGER = system("""You are synthesizing analyses of sub-sections into understanding
of the whole. You receive labeled analyses of parts; find:
(1) the argumentative arc connecting them,
(2) tensions or contradictions between sections,
(3) what the sequence reveals that the parts individually don't.
200-400 words.""", cache=True)

SPLIT_SCHEMA = {
    "type": "object",
    "properties": {
        "is_leaf": {
            "type": "boolean",
            "description": "True if this should be analyzed as one unit",
        },
        "reasoning": {
            "type": "string",
            "description": "Why split or not (1 sentence)",
        },
        "subtasks": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "label": {"type": "string", "description": "Short thematic label"},
                    "start_paragraph": {"type": "integer"},
                    "end_paragraph": {"type": "integer"},
                },
                "required": ["label", "start_paragraph", "end_paragraph"],
                "additionalProperties": False,
            },
        },
    },
    "required": ["is_leaf", "reasoning", "subtasks"],
    "additionalProperties": False,
}

MODEL = "claude-sonnet-4-6"


def annotate_paragraphs(text: str) -> str:
    """Add paragraph numbers so the splitter can reference them.

    Paragraphs are defined as \\n\\n-separated chunks. This is a simple
    heuristic — texts with \\n\\n inside quoted passages or code blocks
    will split at those points too. For such texts, use a format-aware
    splitter instead.
    """
    paragraphs = text.split("\n\n")
    lines = []
    for i, p in enumerate(paragraphs):
        if p.strip():
            lines.append(f"[¶{i}] {p.strip()}")
    return f"Text has {len(paragraphs)} paragraphs.\n\n" + "\n\n".join(lines)


async def main():
    data_path = Path(__file__).parent / "data" / "genealogy_first_essay.txt"
    essay = data_path.read_text()
    n_paras = len(essay.split("\n\n"))

    print(f"Text: Nietzsche, Genealogy of Morals, First Essay")
    print(f"  {len(essay)} chars, {n_paras} paragraphs")
    print("=" * 70)

    trace = Trace()
    display = LiveFlowDisplay()
    flow.observe(trace, display)

    async with display:
        result = await flow.tree(
            task=essay,
            split_fn=lambda t: SPLITTER | user(annotate_paragraphs(t)),
            split_schema=SPLIT_SCHEMA,
            leaf_fn=lambda t: ANALYZER | user(t),
            merge_fn=lambda results, labels: MERGER | user(
                Block.join(results, labels=labels)
            ),
            model_split=MODEL,
            model_leaf=MODEL,
            model_merge=MODEL,
            max_depth=3,
            label="Genealogy, First Essay",
        )

    flow.clear_observers()

    print("\n" + "=" * 70)
    print("SYNTHESIS")
    print("=" * 70)
    print(result)
    print()
    print(f"Trace: {len(trace)} events, {trace.total_elapsed:.1f}s")

    trace.save("/tmp/tree_trace.json")

    output_path = Path(__file__).parent / "output" / "genealogy_tree.md"
    output_path.parent.mkdir(exist_ok=True)
    output_path.write_text(
        f"# Tree Decomposition: Nietzsche, Genealogy of Morals, First Essay\n\n"
        f"> Generated by `examples/tree_decomposition.py`\n>\n"
        f"> {len(trace)} events, {trace.total_elapsed:.1f}s\n\n"
        f"---\n\n{result}\n"
    )
    print(f"Output saved to {output_path}")


if __name__ == "__main__":
    asyncio.run(main())
